export const GETTING_A_RESOURCE_BY_ID= "GETTING_A_RESOURCE_BY_ID";
export const LISTING_ALL_RESOURCES= "LISTING_ALL_RESOURCES";
export const CREATING_A_RESOURCE= "CREATING_A_RESOURCE";
export const UPDATING_A_RESOURCE ="UPDATING_A_RESOURCE";
export const PATCHING_A_RESOURCE ="PATCHING_A_RESOURCE";
export const DELETING_A_RESOURCE ="DELETING_A_RESOURCE";
export const ADD_ERROR ="ADD_ERROR";
export const REMOVE_ERROR ="REMOVE_ERROR"
